export const Navigation = 'id0'
export const PopoverAppBarInfo = 'id1'
export const PopoverAppBarSettings = 'id2'
export const PopoverAppBarSettingsAnimation = 'id3'
export const PopoverAppBarSettingsTheme = 'id4'
export const PopoverAppBarSettingsGrouping = 'id5'
export const PopoverAppBarSettingsDecimal = 'id6'

export const PageBasicInput = 'id7'
export const PageBasicOutput = 'id8'

export const PageScientificAngle = 'id9'
export const PageScientificInput = 'id10'
export const PageScientificOutput = 'id11'
export const PageScientificFunctionButton = 'id12'
export const PageScientificFunctionPopover = 'id13'
export const PageScientificFunctionInverse = 'id14'
export const PageScientificFunctionHyperbolic = 'id15'

export const PageConverterOptions = 'id16'
export const PageConverterInput = 'id17'
export const PageConverterOutput = 'id18'
export const PageConverterType = 'id19'
export const PageConverterSwap = 'id20'
export const PageConverterInputUnit = 'id21'
export const PageConverterOutputUnit = 'id22'

export const PageProgrammerInput = 'id23'
export const PageProgrammerNumTypes = 'id24'
export const PageProgrammerOutputDec = 'id25'
export const PageProgrammerOutputHex = 'id26'
export const PageProgrammerOutputOct = 'id27'
export const PageProgrammerOutputBin = 'id28'

export const PageDateOperation = 'id29'
export const PageDateOutput = 'id30'
export const PageDateDiff = 'id31'
export const PageDateAddOrSub = 'id32'
export const PageDateYears = 'id33'
export const PageDateMonths = 'id34'
export const PageDateDays = 'id35'
export const PageDateFrom = 'id36'
export const PageDateTo = 'id37'