export const Navigation = 'id0'
export const PopoverAppBarInfo = 'id1'
export const PopoverAppBarSettings = 'id2'
export const PopoverAppBarSettingsAnimation = 'id3'
export const PopoverAppBarSettingsTheme = 'id4'
export const PopoverAppBarSettingsGrouping = 'id5'
export const PopoverAppBarSettingsDecimal = 'id6'