export const PopoverAppBarInfo = '74EB4B1A'
export const PopoverAppBarInfoShare = 'FC9B52D1'
export const PopoverAppBarSettings = 'FFBBE90C'
export const PopoverAppBarSettingsAnimation = 'F6241AE6'
export const PopoverAppBarSettingsTheme = '769E54AD'