export const PopoverAppBarInfo = '74EB4B1A'
export const PopoverAppBarInfoShare = 'FC9B52D1'

export const PopoverAppBarSettings = 'FFBBE90C'
export const PopoverAppBarSettingsAnimation = 'F6241AE6'
export const PopoverAppBarSettingsTheme = '769E54AD'
export const PopoverAppBarSettingsTextWrap = 'B9B1D37C'
export const PopoverAppBarSettingsMinifyCSS = '9A87AA6E'

export const PopoverAppBarMore = '6902697A'
export const PopoverAppBarMoreOpenFile = 'C69D93CB'
export const PopoverAppBarMoreResetSASS = '74FC190E'
export const PopoverAppBarMoreResetSCSS = '06A7BC3F'
export const PopoverAppBarMoreCopy = '72BAAFFF'
export const PopoverAppBarMoreCopySASS = '1E0733FE'
export const PopoverAppBarMoreCopySCSS = 'D0EC685E'
export const PopoverAppBarMoreCopyCSS = 'D75B535A'
export const PopoverAppBarMoreDownload = '976FA8BB'
export const PopoverAppBarMoreDownloadSASS = '213928E2'
export const PopoverAppBarMoreDownloadSCSS = 'C7F2E81A'
export const PopoverAppBarMoreDownloadCSS = 'EBEED3A1'

export const InputContainer = 'FD97CC4D'
export const InputTabs = '6E0947FC'
export const InputSASS = '26EE4FD5'
export const InputSCSS = 'B5B2E4B8'
export const Slider = '10EC713D'
export const OutputCSS = 'BE380885'