export const AppBarInfo = '74EB4B1A'
export const AppBarInfoShare = 'FC9B52D1'

export const AppBarSettings = 'FFBBE90C'
export const AppBarSettingsAnimation = 'F6241AE6'
export const AppBarSettingsTheme = '769E54AD'
export const AppBarSettingsTextWrap = 'CDDAFBDA'
export const AppBarSettingsModule = '2EDA31D2'
export const AppBarSettingsKeepFnNames = '06D9C727'
export const AppBarSettingsKeepClsNames = 'CA6954D8'
export const AppBarSettingsTopLevel = 'CA9EF2AC'
export const AppBarSettingsBeautify = 'A03D3A69'

export const AppBarMore = '6DFDEBAD'
export const AppBarMoreOpenFile = 'C843F8A3'
export const AppBarMoreReset = '2251B39D'
export const AppBarMoreCopy = 'C123C368'
export const AppBarMoreDownload = '9B846CAF'

export const InputContainer = 'FD97CC4D'
export const Input = '26EE4FD5'
export const Slider = '10EC713D'
export const Output = 'BE380885'