export const Backspace = 'Backspace'
export const Enter = 'Enter'
export const Delete = 'Delete'
export const Equal = '='
export const Space = ' '
export const Plus = '+'
export const Minus = '-'
export const Underscore = '_'
export const Escape = 'Escape'
export const ArrowDown = 'ArrowDown'
export const ArrowUp = 'ArrowUp'
export const ArrowLeft = 'ArrowLeft'
export const ArrowRight = 'ArrowRight'