export enum RoutesLinks {
	home = '/',
	apps = '/apps',
	privacy = '/privacy',
	terms = '/terms',
	about = '/about',
	error = '404',

	// apps
	randomizer = '/a/randomizer',
	markdownConverter = '/a/markdown-converter',
	colorGenerator = '/a/color-generator',
	calculator = '/a/calculator',
	sassConverter = '/a/sass-converter',
	battery = '/a/battery',
	qrCode = '/a/qr-code',
	colorGradient = '/a/color-gradient',
	emojiPicker = '/a/emoji-picker',
	latexViewer = '/a/latex-viewer',
	colorPicker = '/a/color-picker',
	clock = '/a/clock',
	xmlEscape = '/a/xml-escape',
	javascriptMinifier = '/a/javascript-minifier',
	mediaPlayer = '/a/media-player',
	urlEncoder = '/a/url-encoder',
	deadPixelTest = '/a/dead-pixel-test',
	geolocation = '/a/geolocation',
	compass = '/a/compass',
	networkInformation = '/a/network-information',
	vibrator = '/a/vibrator',

	// TODO: create these apps
	cssUnitConverter = '/a/css-unit-converter',
	contrastChecker = '/a/contrast-checker',
	shadowGenerator = '/a/shadow-generator',
	sensor = '/a/sensor',
	screenRecorder = '/a/screen-recorder',
	keyboardTest = '/a/keyboard-test',
	voiceRecorder = '/a/voice-recorder',
	tasks = '/a/tasks',
	notes = '/a/notes',
	codeFormatter = '/a/code-formatter',
	whiteboard = '/a/whiteboard',
	stopwatch = '/a/stopwatch',
	weather = '/a/weather',
	calendar = '/a/calendar',
	document = '/a/document',
	sheet = '/a/sheet',
	presentation = '/a/presentation',
	favicon = '/a/favicon',
	audioEditor = '/a/audio-editor',
	videoEditor = '/a/video-editor',
	imageEditor = '/a/image-editor',
	imageConverter = '/a/image-converter',
	sorter = '/a/sorter',
	textEditor = '/a/text-editor',
}

export enum ExternalLinks {
	siteUrl = 'https://redmerah.com',
	contactEmail = 'redmerah1813@gmail.com',
	donate = 'https://buymeacoffee.com/msulais',
}