export enum RoutesLinks {
	home = '/',
	apps = '/apps',
	privacy = '/privacy',
	terms = '/terms',
	about = '/about',
	error = '404',

	// apps
	randomizer = '/randomizer',
	markdownConverter = '/markdown-converter',
	colorGenerator = '/color-generator',
	calculator = '/calculator',
	sassConverter = '/sass-converter',
	battery = '/battery',
	qrCode = '/qr-code',
	colorGradient = '/color-gradient',
	emojiPicker = '/emoji-picker',
	latexViewer = '/latex-viewer',
	colorPicker = '/color-picker',
	clock = '/clock',
	xmlEscape = '/xml-escape',
	javascriptMinifier = '/javascript-minifier',
	mediaPlayer = '/media-player',
	urlEncoder = '/url-encoder',
	deadPixelTest = '/dead-pixel-test',
	geolocation = '/geolocation',
	compass = '/compass',
	networkInformation = '/network-information',
	vibrator = '/vibrator',

	// TODO: create these apps
	contrastChecker = '/contrast-checker',
	sensor = '/sensor',
	screenRecorder = '/screen-recorder',
	keyboardTest = '/keyboard-test',
	voiceRecorder = '/voice-recorder',
	tasks = '/tasks',
	notes = '/notes',
	codeFormatter = '/code-formatter',
	whiteboard = '/whiteboard',
	stopwatch = '/stopwatch',
	weather = '/weather',
	calendar = '/calendar',
	document = '/document',
	sheet = '/sheet',
	presentation = '/presentation',
	favicon = '/favicon',
	audioEditor = '/audio-editor',
	videoEditor = '/video-editor',
	imageEditor = '/image-editor',
	imageConverter = '/image-converter',
	sorter = '/sorter',
	textEditor = '/text-editor',
}

export enum ExternalLinks {
	siteUrl = 'https://redmerah.com',
	contactEmail = 'redmerah1813@gmail.com',
	donate = 'https://buymeacoffee.com/redmerah',
}