export const PopoverAppBarInfo = '74EB4B1A'
export const PopoverAppBarInfoShare = 'FC9B52D1'

export const PopoverAppBarSettings = 'FFBBE90C'
export const PopoverAppBarSettingsAnimation = 'F6241AE6'
export const PopoverAppBarSettingsTheme = '769E54AD'
export const PopoverAppBarSettingsTextWrap = '244343CF'

export const PopoverAppBarMore = '6902697A'
export const PopoverAppBarMoreOpenFile = 'C69D93CB'
export const PopoverAppBarMorePrint = 'CF21B51B'
export const PopoverAppBarMoreResetMarkdown = '06A7BC3F'
export const PopoverAppBarMoreResetCSS = '74FC190E'
export const PopoverAppBarMoreCopy = '72BAAFFF'
export const PopoverAppBarMoreCopyMarkdown = '1E0733FE'
export const PopoverAppBarMoreCopyCSS = 'D0EC685E'
export const PopoverAppBarMoreCopyHTML = 'D75B535A'
export const PopoverAppBarMoreDownload = '976FA8BB'
export const PopoverAppBarMoreDownloadMarkdown = '213928E2'
export const PopoverAppBarMoreDownloadCSS = 'C7F2E81A'
export const PopoverAppBarMoreDownloadHTML = 'EBEED3A1'

export const InputContainer = 'FD97CC4D'
export const InputTabs = '6E0947FC'
export const OutputTabs = '33FD3528'
export const InputMarkdown = '26EE4FD5'
export const InputCSS = 'B5B2E4B8'
export const Slider = '10EC713D'
export const OutputHTML = 'BE380885'
export const OutputPreview = '456FF053'