export const PopoverAppBarInfo = 'CD6EF18D'
export const PopoverAppBarInfoShare = 'FC9B52D1'
export const PopoverAppBarSettings = '48A3132E'
export const PopoverAppBarSettingsAnimation = '954B589B'
export const PopoverAppBarSettingsTheme = '1EB4E61F'

export const CopyButton = 'C05FBD3B'
export const ColorInput = 'A41F4D7F'
export const ColorInputLabel = '948094CA'
export const AccentLight = '9BA48ED0'
export const AccentLightText = '3774EE76'
export const OnAccentLightText = 'C9FFA8C6'
export const AccentDark = '58FDD62E'
export const AccentDarkText = 'E07DF42E'
export const OnAccentDarkText = 'DC7685AF'