let _ID_INDEX = 0

function _createId(): string {
	++_ID_INDEX
	return 'app-' + _ID_INDEX
}

export class ElementIds {
	static readonly appbar = _createId()
	static readonly appbarSideBarButton = _createId()
	static readonly appbarInfoButton = _createId()
	static readonly appbarInfoMenu = _createId()
	static readonly appbarInfoMenuShareButton = _createId()
	static readonly appbarSettingsButton = _createId()
	static readonly appbarSettingsMenu = _createId()
	static readonly appbarSettingsAnimationMenu = _createId()
	static readonly appbarSettingsThemeMenu = _createId()
	static readonly appbarSettingsDecimalMenu = _createId()
	static readonly appbarSettingsGroupMenu = _createId()
	static readonly bodyBasic = _createId()
	static readonly bodyBasicInput = _createId()
	static readonly bodyBasicOutput = _createId()
	static readonly bodyConverter = _createId()
	static readonly bodyConverterOptions = _createId()
	static readonly bodyConverterInput = _createId()
	static readonly bodyConverterOutput = _createId()
	static readonly bodyConverterType = _createId()
	static readonly bodyConverterSwap = _createId()
	static readonly bodyConverterInputUnit = _createId()
	static readonly bodyConverterOutputUnit = _createId()
	static readonly bodyDate = _createId()
	static readonly bodyDateOperation = _createId()
	static readonly bodyDateOperationDifference = _createId()
	static readonly bodyDateOperationAddSubtract = _createId()
	static readonly bodyDateInputYears = _createId()
	static readonly bodyDateInputMonths = _createId()
	static readonly bodyDateInputDays = _createId()
	static readonly bodyDateInputFromButton = _createId()
	static readonly bodyDateInputToButton = _createId()
	static readonly bodyDateInputFromDatePicker = _createId()
	static readonly bodyDateInputToDatePicker = _createId()
	static readonly bodyDateOutput = _createId()
	static readonly bodyProgrammer = _createId()
	static readonly bodyProgrammerInput = _createId()
	static readonly bodyProgrammerOutput = _createId()
	static readonly bodyProgrammerOutputDec = _createId()
	static readonly bodyProgrammerOutputHex = _createId()
	static readonly bodyProgrammerOutputOct = _createId()
	static readonly bodyProgrammerOutputBin = _createId()
	static readonly bodyScientific = _createId()
	static readonly bodyScientificAngle = _createId()
	static readonly bodyScientificInput = _createId()
	static readonly bodyScientificOutput = _createId()
	static readonly bodyScientificFunctionButton = _createId()
	static readonly bodyScientificFunctionMenu = _createId()
	static readonly bodyScientificFunctionInvers = _createId()
	static readonly bodyScientificFunctionHyperbolic = _createId()
	static readonly navigationSideBar = _createId()
	static readonly navigationDrawer = _createId()
}