import { _basic, _scientific, _converter, _programmer, _date } from "@/data/string";
import { CalculatorType } from "./_enums";
import { ConverterType } from "./_converter";

export const 
    SIZE_SIDE_NAVIGATION_NONE = 640, 
    SIZE_SIDE_NOTEBOOK_NONE = 760,
    CALCULATOR_TYPES = [
        { icon: 0xE2C6, type: CalculatorType[_basic], text: 'Basic' },
        { icon: 0xE1C1, type: CalculatorType[_scientific], text: 'Scientific' },
        { icon: 0xE123, type: CalculatorType[_converter], text: 'Converter' },
        { icon: 0xE4A8, type: CalculatorType[_programmer], text: 'Programmer' },
        { icon: 0xE2CC, type: CalculatorType[_date], text: 'Date' },
    ],
    KEY_DIVISION = "÷",
    KEY_MULTIPLY = "×",
    KEY_SQUARE_ROOT = "√", 
    CONVERTER_TYPES = [
        { icon: 0xED6B, type: ConverterType.angle, text: 'Angle' },
        { icon: 0xE82F, type: ConverterType.area, text: 'Area' },
        { icon: 0xED15, type: ConverterType.frequency, text: 'Frequency' },
        { icon: 0xED9B, type: ConverterType.length, text: 'Length' },
        { icon: 0xE0F5, type: ConverterType.pressure, text: 'Pressure' },
        { icon: 0xF048, type: ConverterType.temperature, text: 'Temperature' },
        { icon: 0xF1DD, type: ConverterType.time, text: 'Time' },
        { icon: 0xE252, type: ConverterType.volume, text: 'Volume' },
        { icon: 0xE731, type: ConverterType.weight, text: 'Weight & Mass' },
    ],
    _toggle_navigation_expand = 'toggle_navigation_expand', 
    _toggle_notebook_expand = 'toggle_notebook_expand', 
    _change_settings_numberFormatGrouping = 'change_settings_numberFormatGrouping',
    _change_settings_numberFormatDecimal = 'change_settings_numberFormatDecimal',
    _toggle_settings_scientificNotation = 'toggle_settings_scientificNotation',
    _toggle_settings_memoryButtons = 'toggle_settings_memoryButtons', 
    _change_calculator_input = 'change_calculator_input',
    _add_memory = 'add_memory', 
    _subtract_memory = 'subtract_memory', 
    _clear_memory = 'clear_memory', 
    _toggle_settings_scientific_angle = 'toggle_settings_scientific_angle', 
    _change_settings_converter_type = 'change_settings_converter_type',
    _change_settings_converter_inputUnit = 'change_settings_converter_inputUnit',
    _change_settings_converter_outputUnit = 'change_settings_converter_outputUnit',
    _change_settings_converter_swapUnit = 'change_settings_converter_swapUnit',
    _change_settings_programmer_numberType = 'change_settings_programmer_numberType',
    _change_settings_date_operation = 'change_settings_date_operation',
    _lastInput_basic = 'lastInput_basic',
    _lastInput_scientific = 'lastInput_scientific',
    _lastInput_converter = 'lastInput_converter',
    _lastInput_programmer = 'lastInput_programmer',
    _lastInput_date_from = 'lastInput_date_from',
    _lastInput_date_to = 'lastInput_date_to',
    _lastInput_date_year = 'lastInput_date_year',
    _lastInput_date_month = 'lastInput_date_month',
    _lastInput_date_day = 'lastInput_date_day',
    _lastOutput_basic = 'lastOutput_basic',
    _lastOutput_scientific = 'lastOutput_scientific',
    _lastOutput_converter = 'lastOutput_converter',
    _lastOutput_programmer = 'lastOutput_programmer',
    _lastOutput_date = 'lastOutput_date',
    _miscellaneous_lastPage = 'miscellaneous_lastPage',
    _miscellaneous_note = 'miscellaneous_note',
    _settings_numberFormat_decimal = 'settings_numberFormat_decimal',
    _settings_numberFormat_grouping = 'settings_numberFormat_grouping', 
    _settings_scientificNotation = 'settings_scientificNotation',
    _settings_memoryButtons = 'settings_memoryButtons', 
    _settings_converter_type = 'settings_converter_type',
    _settings_converter_inputUnit = 'settings_converter_inputUnit',
    _settings_converter_outputUnit = 'settings_converter_outputUnit',
    _settings_scientific_angle = 'settings_scientific_angle', 
    _settings_programmer_numberType = 'settings_programmer_numberType',
    _settings_date_operation = 'settings_date_operation'
;