import { Pages } from "./_enums"

export const SIZE_SIDE_NAVIGATION_NONE = 640
export const PAGES = [
	{type: Pages.button, text: 'Buttons'},
	{type: Pages.checkbox, text: 'CheckBox'},
	{type: Pages.colorpicker, text: 'ColorPicker'},
	{type: Pages.datepicker, text: 'DatePicker'},
	{type: Pages.datetimepicker, text: 'DateTimePicker'},
	{type: Pages.dialog, text: 'Dialog'},
	{type: Pages.divider, text: 'Divider'},
	{type: Pages.drawer, text: 'Drawer'},
	{type: Pages.dropdown, text: 'Dropdown'},
	{type: Pages.emoji, text: 'Emoji'},
	{type: Pages.emojipicker, text: 'EmojiPicker'},
	{type: Pages.expander, text: 'Expander'},
	{type: Pages.icon, text: 'Icon'},
	{type: Pages.list, text: 'List'},
	{type: Pages.menu, text: 'Menu'},
	{type: Pages.modal, text: 'Modal'},
	{type: Pages.popover, text: 'Popover'},
	{type: Pages.switch, text: 'Switch'},
	{type: Pages.textfield, text: 'TextField'},
	{type: Pages.toast, text: 'Toast'},
	{type: Pages.tooltip, text: 'Tooltip'},
]
export const ALL_PAGES_ENUM = [
	Pages.button,
	Pages.checkbox,
	Pages.colorpicker,
	Pages.datepicker,
	Pages.datetimepicker,
	Pages.dialog,
	Pages.divider,
	Pages.drawer,
	Pages.dropdown,
	Pages.emoji,
	Pages.emojipicker,
	Pages.expander,
	Pages.icon,
	Pages.list,
	Pages.menu,
	Pages.modal,
	Pages.popover,
	Pages.textfield,
	Pages.toast,
	Pages.tooltip,
	Pages.switch,
]