export const ELEMENT_ID_PREFIX = 'ID-'

/** must prefix with `'ID-'` */
export enum ElementIds {
	appbar,
	appbarInfoButton,
	appbarInfoMenu,
	appbarInfoShareButton,
	appbarSettingsButton,
	appbarSettingsMenu,
	appbarSettingsAnimationMenu,
	appbarSettingsThemeMenu,
	navigation,
	panelButtons,
	panelButtonsPreview1,
	panelButtonsPreview2,
	panelButtonsPreview3,
	panelButtonsOptions,
	panelButtonsOptionsVariant,
	panelButtonsOptionsVariantLabel,
	panelButtonsOptionsDisabled,
	panelButtonsOptionsFocused,
	panelCheckbox,
	panelCheckboxOptions,
	panelCheckboxPreview1,
	panelCheckboxPreview2,
	panelCheckboxPreview3,
	panelCheckboxOptionsDisabled,
	panelColorpicker,
	panelColorpickerOptions,
	panelColorpickerOptionsHueOnly,
	panelColorpickerOptionsDisabledOpacity,
	panelColorpickerPreviewButton,
	panelColorpickerPreviewColorPicker,
	panelTextfield,
	panelTextfieldPreview,
	panelTextfieldPreviewInput,
	panelTextfieldPreviewLeading,
	panelTextfieldPreviewTrailing,
	panelTextfieldOptions,
	panelTextfieldOptionsType,
	panelTextfieldOptionsTypeLabel,
	panelTextfieldOptionsLeading,
	panelTextfieldOptionsTrailing,
	panelTextfieldOptionsReadonly,
	panelTextfieldOptionsPlaceholder,
}

export enum RadioGroupNames {
	settingsAnimation = 'settings:animation',
	settingsTheme = 'settings:theme',
}