export const ELEMENT_ID_PREFIX = 'ID-'

/** must prefix with `'ID-'` */
export enum ElementIds {
	appbar,
	appbarInfoButton,
	appbarInfoMenu,
	appbarInfoShareButton,
	appbarSettingsButton,
	appbarSettingsMenu,
	appbarSettingsAnimationMenu,
	appbarSettingsThemeMenu,
	appbarSettingsAccentButton,
	appbarColorPicker,
	navigation,
	panelButtons,
	panelButtonsPreview1,
	panelButtonsPreview2,
	panelButtonsPreview3,
	panelButtonsOptions,
	panelButtonsOptionsVariant,
	panelButtonsOptionsVariantLabel,
	panelButtonsOptionsDisabled,
	panelButtonsOptionsFocused,
	panelCheckbox,
	panelCheckboxOptions,
	panelCheckboxPreview1,
	panelCheckboxPreview2,
	panelCheckboxPreview3,
	panelCheckboxOptionsDisabled,
	panelColorpicker,
	panelColorpickerOptions,
	panelColorpickerOptionsHueOnly,
	panelColorpickerOptionsDisabledOpacity,
	panelColorpickerPreviewButton,
	panelColorpickerPreviewColorPicker,
	panelIcon,
	panelIconPreview,
	panelIconOptions,
	panelIconOptionsFilled,
	panelList,
	panelListPreviewList,
	panelListPreviewTitle,
	panelListPreviewLeading,
	panelListPreviewTrailing,
	panelListPreviewSubtitle,
	panelListOptions,
	panelListOptionsVariant,
	panelListOptionsVariantLabel,
	panelListOptionsTrailing,
	panelListOptionsLeading,
	panelListOptionsSubtitle,
	panelListOptionsTitle,
	panelPopover,
	panelPopoverPreviewPopover,
	panelPopoverPreviewButtonOpen,
	panelPopoverPreviewButtonClose,
	panelPopoverOptions,
	panelPopoverOptionsPosition,
	panelPopoverOptionsPositionLabel,
	panelPopoverOptionsPadding,
	panelPopoverOptionsGap,
	panelPopoverOptionsAnchor,
	panelPopoverOptionsAutofocus,
	panelPopoverOptionsImportant,
	panelPopoverOptionsDraggable,
	panelTextfield,
	panelTextfieldPreview,
	panelTextfieldPreviewInput,
	panelTextfieldPreviewLeading,
	panelTextfieldPreviewTrailing,
	panelTextfieldOptions,
	panelTextfieldOptionsType,
	panelTextfieldOptionsTypeLabel,
	panelTextfieldOptionsLeading,
	panelTextfieldOptionsTrailing,
	panelTextfieldOptionsReadonly,
	panelTextfieldOptionsPlaceholder,
}

export enum RadioGroupNames {
	settingsAnimation = 'settings:animation',
	settingsTheme = 'settings:theme',
}